import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const languages = {
  en: {
    name: 'English',
    code: 'en',
    flag: '🇺🇸'
  },
  hi: {
    name: 'हिंदी',
    code: 'hi',
    flag: '🇮🇳'
  },
  es: {
    name: 'Español',
    code: 'es',
    flag: '🇪🇸'
  },
  fr: {
    name: 'Français',
    code: 'fr',
    flag: '🇫🇷'
  },
  de: {
    name: 'Deutsch',
    code: 'de',
    flag: '🇩🇪'
  }
};

export const translations = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.skills': 'Skills',
    'nav.projects': 'Projects',
    'nav.contact': 'Contact',
    'hero.greeting': 'Hi, I\'m',
    'hero.title': 'Full Stack Developer & Problem Solver',
    'hero.subtitle': 'Building exceptional digital experiences',
    'hero.resume': 'Download Resume',
    'about.title': 'About Me',
    'about.description': 'I am a passionate full-stack developer with a strong foundation in programming and a love for creating innovative solutions.',
    'about.hobbies.reading': 'Reading',
    'about.hobbies.reading.desc': 'Exploring new perspectives through books',
    'about.hobbies.music': 'Music',
    'about.hobbies.music.desc': 'Finding inspiration in melodies',
    'about.hobbies.coding': 'Coding',
    'about.hobbies.coding.desc': 'Building innovative solutions',
    'skills.title': 'Skills & Technologies',
    'skills.description': 'A comprehensive overview of my technical expertise',
    'skills.frontend': 'Frontend Development',
    'skills.backend': 'Backend Development',
    'skills.programming': 'Programming',
    'skills.devops': 'DevOps & Cloud',
    'skills.architecture': 'System Architecture',
    'skills.design': 'UI/UX Design',
    'skills.additional': 'Additional Expertise',
    'skills.level.expert': 'Expert',
    'skills.level.advanced': 'Advanced',
    'skills.level.intermediate': 'Intermediate',
    'projects.title': 'Featured Projects',
    'projects.description': 'A collection of projects showcasing my expertise',
    'projects.viewLive': 'View Live',
    'projects.viewCode': 'View Code',
    'projects.technologies': 'Technologies Used',
    'projects.features': 'Key Features',
    'projects.process': 'Development Process',
    'projects.challenges': 'Challenges & Solutions',
    'projects.more': 'more',
    'contact.title': 'Get In Touch',
    'contact.description': 'Feel free to reach out for collaborations or just a friendly hello',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.connect': 'Connect on LinkedIn',
    'footer.brand': 'Full Stack Developer specializing in building exceptional digital experiences.',
    'footer.connect': 'Connect',
    'footer.rights': 'All rights reserved.',
    'footer.location': 'Based in India • Available for Remote Work • Open to Relocation',
    'chat.greeting': 'Hi! I\'m Dainwi\'s assistant. How can I help you today?',
    'chat.placeholder': 'Type your message...',
    'chat.send': 'Send',
    'chat.title': 'Chat Support'
  },
  hi: {
    'nav.home': 'होम',
    'nav.about': 'परिचय',
    'nav.skills': 'कौशल',
    'nav.projects': 'प्रोजेक्ट्स',
    'nav.contact': 'संपर्क',
    'hero.greeting': 'नमस्ते, मैं हूं',
    'hero.title': 'फुल स्टैक डेवलपर और प्रॉब्लम सॉल्वर',
    'hero.subtitle': 'उत्कृष्ट डिजिटल अनुभव बनाना',
    'hero.resume': 'रेज्यूमे डाउनलोड करें',
    'about.title': 'मेरे बारे में',
    'about.description': 'मैं एक जुनूनी फुल-स्टैक डेवलपर हूं जो नवीन समाधान बनाने का शौक रखता है।',
    'about.hobbies.reading': 'पढ़ना',
    'about.hobbies.reading.desc': 'नवीन दृष्टियों को बुनियादी विचारों के माध्यम से खोजना',
    'about.hobbies.music': 'संगीत',
    'about.hobbies.music.desc': 'गीतों से प्रेरणा पाना',
    'about.hobbies.coding': 'कोडिंग',
    'about.hobbies.coding.desc': 'नवीन समाधान बनाना',
    'skills.title': 'कौशल और तकनीकें',
    'skills.description': 'मेरी तकनीकी विशेषज्ञता का एक व्यापक अवलोकन',
    'skills.frontend': 'फ्रंटएंड डेवलपमेंट',
    'skills.backend': 'बैकएंड डेवलपमेंट',
    'skills.programming': 'प्रोग्रामिंग',
    'skills.devops': 'डेवॉप्स और क्लाउड',
    'skills.architecture': 'सिस्टम आर्किटेक्चर',
    'skills.design': 'यूआई/यूएक्स डिजाइन',
    'skills.additional': 'अतिरिक्त विशेषज्ञता',
    'skills.level.expert': 'विशेषज्ञ',
    'skills.level.advanced': 'उन्नत',
    'skills.level.intermediate': 'मध्यम',
    'projects.title': 'प्रमुख प्रोजेक्ट्स',
    'projects.description': 'मेरी विशेषज्ञता को प्रदर्शित करने वाली परियोजनाएं',
    'projects.viewLive': 'लाइव देखें',
    'projects.viewCode': 'कोड देखें',
    'projects.technologies': 'उपयोग किए गए तकनीक',
    'projects.features': 'मुख्य विशेषताएं',
    'projects.process': 'विकास प्रक्रिया',
    'projects.challenges': 'चुनौतियों और समाधान',
    'projects.more': 'अधिक',
    'contact.title': 'संपर्क करें',
    'contact.description': 'सहयोग के लिए संपर्क करें',
    'contact.email': 'ईमेल',
    'contact.phone': 'फोन',
    'contact.connect': 'लिंक्डइन पर संपर्क करें',
    'footer.brand': 'फुल स्टैक डेवलपर जो उत्कृष्ट डिजिटल अनुभव बनाने का शौक रखता है।',
    'footer.connect': 'संपर्क करें',
    'footer.rights': 'सभी अधिकार सुरक्षित हैं।',
    'footer.location': 'भारत में आधारित • रिमोट वर्क के लिए उपलब्ध • रिलोकेशन के लिए खुला है',
    'chat.greeting': 'नमस्ते! मैं Dainwi का सहायक हूं। मैं आपको आज कैसे मदद कर सकता हूं?',
    'chat.placeholder': 'अपनी संदेश टाइप करें...',
    'chat.send': 'भेजें',
    'chat.title': 'चैट सहायक'
  },
  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Sobre mí',
    'nav.skills': 'Habilidades',
    'nav.projects': 'Proyectos',
    'nav.contact': 'Contacto',
    'hero.greeting': 'Hola, soy',
    'hero.title': 'Desarrollador Full Stack y Solucionador de Problemas',
    'hero.subtitle': 'Construyendo experiencias digitales excepcionales',
    'hero.resume': 'Descargar CV',
    'about.title': 'Sobre mí',
    'about.description': 'Soy un desarrollador full-stack apasionado con una sólida base en programación.',
    'about.hobbies.reading': 'Leer',
    'about.hobbies.reading.desc': 'Explorando nuevos puntos de vista a través de libros',
    'about.hobbies.music': 'Música',
    'about.hobbies.music.desc': 'Encontrando inspiración en las melodías',
    'about.hobbies.coding': 'Programación',
    'about.hobbies.coding.desc': 'Construyendo soluciones innovadoras',
    'skills.title': 'Habilidades y Tecnologías',
    'skills.description': 'Una visión general de mi experiencia técnica',
    'skills.frontend': 'Desarrollo Frontend',
    'skills.backend': 'Desarrollo Backend',
    'skills.programming': 'Programación',
    'skills.devops': 'DevOps y Cloud',
    'skills.architecture': 'Arquitectura del Sistema',
    'skills.design': 'Diseño UX/UI',
    'skills.additional': 'Especialización Adicional',
    'skills.level.expert': 'Experto',
    'skills.level.advanced': 'Avanzado',
    'skills.level.intermediate': 'Intermedio',
    'projects.title': 'Proyectos Destacados',
    'projects.description': 'Una colección de proyectos que muestran mi experiencia',
    'projects.viewLive': 'Ver en vivo',
    'projects.viewCode': 'Ver código',
    'projects.technologies': 'Tecnologías Utilizadas',
    'projects.features': 'Características Clave',
    'projects.process': 'Proceso de Desarrollo',
    'projects.challenges': 'Desafíos y Soluciones',
    'projects.more': 'más',
    'contact.title': 'Contacto',
    'contact.description': 'No dudes en contactarme para colaboraciones',
    'contact.email': 'Correo',
    'contact.phone': 'Teléfono',
    'contact.connect': 'Conectarse en LinkedIn',
    'footer.brand': 'Desarrollador Full Stack especializado en construir experiencias digitales excepcionales.',
    'footer.connect': 'Conectarse',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.location': 'Basado en India • Disponible para Trabajo Remoto • Abierto a Reubicación',
    'chat.greeting': 'Hola! Soy el asistente de Dainwi. ¿Cómo puedo ayudarte hoy?',
    'chat.placeholder': 'Escribe tu mensaje...',
    'chat.send': 'Enviar',
    'chat.title': 'Soporte de Chat'
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.skills': 'Compétences',
    'nav.projects': 'Projets',
    'nav.contact': 'Contact',
    'hero.greeting': 'Bonjour, je suis',
    'hero.title': 'Développeur Full Stack et Résolveur de Problèmes',
    'hero.subtitle': 'Construire des expériences numériques exceptionnelles',
    'hero.resume': 'Télécharger CV',
    'about.title': 'À propos de moi',
    'about.description': 'Je suis un développeur full-stack passionné avec une solide base en programmation.',
    'about.hobbies.reading': 'Lire',
    'about.hobbies.reading.desc': 'Explorer de nouvelles perspectives à travers des livres',
    'about.hobbies.music': 'Musique',
    'about.hobbies.music.desc': 'Trouver l\'inspiration dans les mélodies',
    'about.hobbies.coding': 'Programmation',
    'about.hobbies.coding.desc': 'Construire des solutions innovantes',
    'skills.title': 'Compétences et Technologies',
    'skills.description': 'Un aperçu de mon expertise technique',
    'skills.frontend': 'Développement Frontend',
    'skills.backend': 'Développement Backend',
    'skills.programming': 'Programmation',
    'skills.devops': 'DevOps et Cloud',
    'skills.architecture': 'Architecture du Système',
    'skills.design': 'Conception UX/UI',
    'skills.additional': 'Expertise Supplémentaire',
    'skills.level.expert': 'Expert',
    'skills.level.advanced': 'Avancé',
    'skills.level.intermediate': 'Intermédiaire',
    'projects.title': 'Projets Vedettes',
    'projects.description': 'Une collection de projets démontrant mon expertise',
    'projects.viewLive': 'Voir en direct',
    'projects.viewCode': 'Voir le code',
    'projects.technologies': 'Technologies Utilisées',
    'projects.features': 'Fonctionnalités Clés',
    'projects.process': 'Processus de Développement',
    'projects.challenges': 'Défis et Solutions',
    'projects.more': 'plus',
    'contact.title': 'Contact',
    'contact.description': 'N\'hésitez pas à me contacter pour des collaborations',
    'contact.email': 'Email',
    'contact.phone': 'Téléphone',
    'contact.connect': 'Me connecter sur LinkedIn',
    'footer.brand': 'Développeur Full Stack spécialisé dans la création d\'expériences numériques exceptionnelles.',
    'footer.connect': 'Me connecter',
    'footer.rights': 'Tous droits réservés.',
    'footer.location': 'Basé en Inde • Disponible pour Travail à Distance • Ouvert à la Relocation',
    'chat.greeting': 'Bonjour! Je suis votre assistant Dainwi. Comment puis-je vous aider aujourd\'hui?',
    'chat.placeholder': 'Tapez votre message...',
    'chat.send': 'Envoyer',
    'chat.title': 'Support de Chat'
  },
  de: {
    'nav.home': 'Start',
    'nav.about': 'Über mich',
    'nav.skills': 'Fähigkeiten',
    'nav.projects': 'Projekte',
    'nav.contact': 'Kontakt',
    'hero.greeting': 'Hallo, ich bin',
    'hero.title': 'Full Stack Entwickler und Problemlöser',
    'hero.subtitle': 'Exzellente digitale Erfahrungen erstellen',
    'hero.resume': 'Lebenslauf herunterladen',
    'about.title': 'Über mich',
    'about.description': 'Ich bin ein leidenschaftlicher Full-Stack-Entwickler mit soliden Programmierkenntnissen.',
    'about.hobbies.reading': 'Lesen',
    'about.hobbies.reading.desc': 'Neue Perspektiven durch Bücher entdecken',
    'about.hobbies.music': 'Musik',
    'about.hobbies.music.desc': 'Inspiration in Melodien finden',
    'about.hobbies.coding': 'Programmieren',
    'about.hobbies.coding.desc': 'Innovative Lösungen erstellen',
    'skills.title': 'Fähigkeiten und Technologien',
    'skills.description': 'Ein Überblick über meine technische Expertise',
    'skills.frontend': 'Frontend-Entwicklung',
    'skills.backend': 'Backend-Entwicklung',
    'skills.programming': 'Programmierung',
    'skills.devops': 'DevOps und Cloud',
    'skills.architecture': 'Systemarchitektur',
    'skills.design': 'UI/UX-Design',
    'skills.additional': 'Zusätzliche Expertise',
    'skills.level.expert': 'Experte',
    'skills.level.advanced': 'Fortgeschritten',
    'skills.level.intermediate': 'Mittelstufig',
    'projects.title': 'Ausgewählte Projekte',
    'projects.description': 'Eine Sammlung von Projekten, die meine Expertise zeigen',
    'projects.viewLive': 'Live anzeigen',
    'projects.viewCode': 'Code anzeigen',
    'projects.technologies': 'Verwendete Technologien',
    'projects.features': 'Schlüsselmerkmale',
    'projects.process': 'Entwicklungsprozess',
    'projects.challenges': 'Herausforderungen und Lösungen',
    'projects.more': 'mehr',
    'contact.title': 'Kontakt',
    'contact.description': 'Kontaktieren Sie mich gerne für Zusammenarbeit',
    'contact.email': 'E-Mail',
    'contact.phone': 'Telefon',
    'contact.connect': 'Auf LinkedIn verbinden',
    'footer.brand': 'Full Stack Entwickler, der sich auf die Erstellung ausgezeichneter digitaler Erfahrungen spezialisiert.',
    'footer.connect': 'Verbinden',
    'footer.rights': 'Alle Rechte vorbehalten.',
    'footer.location': 'Basierend in Indien • Für Remote-Arbeit verfügbar • Offen für Umzug',
    'chat.greeting': 'Hallo! Ich bin Ihr Assistent Dainwi. Wie kann ich Ihnen heute helfen?',
    'chat.placeholder': 'Geben Sie Ihre Nachricht ein...',
    'chat.send': 'Senden',
    'chat.title': 'Chat-Support'
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  const value = {
    language,
    setLanguage,
    t: (key) => translations[language][key] || key,
    currentLanguage: languages[language]
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
} 